version: "3.7"

services:
  tacos-db:
    image: postgres:13-alpine
    container_name: tacos-db-postgres
    restart: on-failure
    secrets:
      - db-password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=tacos-db
      - POSTGRES_DB=tacos-db
    expose:
      - '5432'
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - private
    volumes:
      - "tacos-db-data:/var/lib/postgresql/data"

  taco-libre:
    build: .
    image: taco-libre:latest
    networks:
      - private
    secrets:
      - db-password
      - slack-sign-secret
    environment:
      - SLACK_SIGN_SECRET=/run/secrets/slack-sign-secret
      - TYPEORM_PASSWORD_FILE=/run/secrets/db-password
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=tacos-db
      - TYPEORM_DATABASE=tacos-db
      - TYPEORM_SYNCHRONIZE=1
      - TYPEORM_HOST=tacos-db
      - TYPEORM_ENTITIES=./entities/*.js
      - TYPEORM_LOGGING=all
      - LEADERBOARD_LIMIT=10
      - SERVER_HOST=localhost
      - SERVER_PORT=80
    container_name: taco-libre
    healthcheck:
      test: curl -f http://localhost/.well-known/server-health || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    depends_on:
      - tacos-db

networks:
  private:

volumes:
  tacos-db-data:

secrets:
  slack-sign-secret:
    file: .docker-secret-slack-sign-secret
  db-password:
    file: .docker-secret-db-password
